### ISSUE TITLE
Execution of native 9a294b2138abb884 in script host failed

### ISSUE THREAD

**Issue by neurogen-dev** [kibook/redm-objectloader#3]
Hello! One of our players reported this issue.

![Screenshot_280](https://user-images.githubusercontent.com/70670181/126451433-f5537296-1119-4626-90c2-18bc92b005bb.png)

**Comment by kibook** [comment]
9a294b2138abb884 is [`CREATE_OBJECT_NO_OFFSET`](https://vespura.com/doc/natives/?_0x9A294B2138ABB884), so the native used to create the objects is failing for some reason. This could be due to having too many objects spawned by scripts in one place. 

Try lowering `Config.MaxEntities` in [config.lua](https://github.com/kibook/redm-objectloader/blob/master/objectloader/config.lua) and see if that removes this error. If it does, then you may have to remove some objects either from your map or that are spawned by other scripts in that area.

You may have better luck converting your map to a ymap instead. ymap is the native game map format (well, one of them) and you can include many more objects using a ymap than you can spawn with scripts before there are issues. If you made the map in singleplayer with Lambdarevolution's map editor, you can try converting it to ymap with this: https://github.com/kibook/lambda2ymap. If you made this with the [spooner](https://github.com/kibook/spooner), you can also export directly to "ymap" in the Import/Export menu, rather than "Map Editor XML".

There are a few issues you may encounter with a ymap, though, that you don't spawning objects by script (e.g., with objectloader):
- ymap only works for objects placed outside of building interiors. If you try to place an object inside with a ymap, the object may appear glitchy and disappear at certain camera angles. There's a different system for placing interior objects, a ytyp file, but I don't have anything to automatically create one yet.
- Vegetation objects don't seem to appear when placed as part of a ymap. I'm not sure why this is, whether they just need a special flag compared to other types of objects, or if there's some other kind of metadata file needed alongside the ymap.

I use ymaps whenever possible, as the native game map format is naturally more stable than a script like objectloader. For the few maps I have that involve interior objects or vegetation, I use objectloader for now until I can resolve those issues.
